on:
  rss:
    url: https://robbinespu.gitlab.io/index.xml
    config:
      limit: 100
jobs:
  request:
    name: Make a HTTP Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actionsflow/axios@v1
        with:
          url: https://ssl.bing.com/webmaster/api.svc/json/SubmitUrl?apikey=${{ secrets.BING_API }}
          method: POST
          #bearer-token: ${{ secrets.MSTDN_ACCESS_TOKEN }}
          data: |
            {
              "siteUrl":"https://robbinespu.gitlab.io",
              "url": "${{ on.rss.outputs.link }}"
            }
